# action.yml
name: "R spell check"
description: "Spell check R, Rmd and md files"
inputs:
  dictionary: # id of input
    description: "Dictionary file path"
    required: true
    default: "components/dictionary.txt"
  files:
    description: Glob of files to check
    required: false
outputs:
  error_count:
    description: The number of spelling errors
runs:
  using: "docker"
  image: docker://ghcr.io/alexslemonade/spellcheck:v0.1.0
  args:
    - ${{ inputs.dictionary || '/dev/null'  }}
    - ${{ inputs.files }}
