on: [push]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spell check action
        uses: ./ # Uses an action in the root directory
        id: spell 
      # Use the output from the `spell check` step
      - name: Get the number of errors
        run: |
          echo "There were ${{ steps.spell.outputs.error_count }} errors"
          cat spell_check_errors.tsv